version: "3"

services: 
  api: 
    restart: always
    build: ./app
    ports:
      - 5000:5000
    volumes:
      - ./app:/app
    depends_on:
      - postgres
    entrypoint: ["python", "api.py"]

  postgres:
    restart: always
    image: postgres
    environment:
      - POSTGRES_USER=lol
      - POSTGRES_PASSWORD=lol
      - POSTGRES_DB=lol
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  spark:
    image: jupyter/all-spark-notebook
    ports:
      - "8888:8888"
      - "4040-4048:4040-4048"
    volumes:
      - ./notebooks:/home/jovyan/work/notebooks/