CREATE TABLE summoner_match_base_stats
(

    summoner_name text NULL,
    summoner_id BIGINT NULL,
    teamId bigint NULL,
	match.gameId bigint NULL,
    match.gameCreation bigint NULL,
    match.gameDuration BIGINT precision NULL,
    match.gameMode text NULL,
    match.gameType text NULL,
    match.seasonId bigint NULL,
    match.win text NULL,
    championId bigint NULL,
    highestAchievedSeasonTier text NULL,
    participantId bigint NULL,
    spell1Id bigint NULL,
    spell2Id bigint NULL,
    stats.assists bigint NULL,
    stats.champLevel bigint NULL,
    stats.combatPlayerScore bigint NULL,
    stats.damageDealtToObjectives bigint NULL,
    stats.damageDealtToTurrets bigint NULL,
    stats.damageSelfMitigated bigint NULL,
    stats.deaths bigint NULL,
    stats.bigintKills bigint NULL,
    stats.firstBloodAssist boolean NULL,
    stats.firstBloodKill boolean NULL,
    stats.firstInhibitorAssist boolean NULL,
    stats.firstInhibitorKill boolean NULL,
    stats.firstTowerAssist boolean NULL,
    stats.firstTowerKill boolean NULL,
    stats.goldEarned bigint NULL,
    stats.goldSpent bigint NULL,
    stats.inhibitorKills bigint NULL,
    stats.item0 bigint NULL,
    stats.item1 bigint NULL,
    stats.item2 bigint NULL,
    stats.item3 bigint NULL,
    stats.item4 bigint NULL,
    stats.item5 bigint NULL,
    stats.item6 bigint NULL,
    stats.killingSprees bigint NULL,
    stats.kills bigint NULL,
    stats.largestCriticalStrike bigint NULL,
    stats.largestKillingSpree bigint NULL,
    stats.largestMultiKill bigint NULL,
    stats.longestTimeSpentLiving bigint NULL,
    stats.magicDamageDealt bigint NULL,
    stats.magicDamageDealtToChampions bigint NULL,
    stats.magicalDamageTaken bigint NULL,
    stats.neutralMinionsKilled bigint NULL,
    stats.neutralMinionsKilledEnemyJungle bigint NULL,
    stats.neutralMinionsKilledTeamJungle bigint NULL,
    stats.objectivePlayerScore bigint NULL,
    stats.participantId bigint NULL,
    stats.pentaKills bigint NULL,
    stats.perk0 bigint NULL,
    stats.perk0Var1 bigint NULL,
    stats.perk0Var2 bigint NULL,
    stats.perk0Var3 bigint NULL,
    stats.perk1 bigint NULL,
    stats.perk1Var1 bigint NULL,
    stats.perk1Var2 bigint NULL,
    stats.perk1Var3 bigint NULL,
    stats.perk2 bigint NULL,
    stats.perk2Var1 bigint NULL,
    stats.perk2Var2 bigint NULL,
    stats.perk2Var3 bigint NULL,
    stats.perk3 bigint NULL,
    stats.perk3Var1 bigint NULL,
    stats.perk3Var2 bigint NULL,
    stats.perk3Var3 bigint NULL,
    stats.perk4 bigint NULL,
    stats.perk4Var1 bigint NULL,
    stats.perk4Var2 bigint NULL,
    stats.perk4Var3 bigint NULL,
    stats.perk5 bigint NULL,
    stats.perk5Var1 bigint NULL,
    stats.perk5Var2 bigint NULL,
    stats.perk5Var3 bigint NULL,
    stats.perkPrimaryStyle bigint NULL,
    stats.perkSubStyle bigint NULL,
    stats.physicalDamageDealt bigint NULL,
    stats.physicalDamageDealtToChampions bigint NULL,
    stats.physicalDamageTaken bigint NULL,
    stats.playerScore0 bigint NULL,
    stats.playerScore1 bigint NULL,
    stats.playerScore2 bigint NULL,
    stats.playerScore3 bigint NULL,
    stats.playerScore4 bigint NULL,
    stats.playerScore5 bigint NULL,
    stats.playerScore6 bigint NULL,
    stats.playerScore7 bigint NULL,
    stats.playerScore8 bigint NULL,
    stats.playerScore9 bigint NULL,
    stats.quadraKills bigint NULL,
    stats.sightWardsBoughtInGame bigint NULL,
    stats.timeCCingOthers bigint NULL,
    stats.totalDamageDealt bigint NULL,
    stats.totalDamageDealtToChampions bigint NULL,
    stats.totalDamageTaken bigint NULL,
    stats.totalHeal bigint NULL,
    stats.totalMinionsKilled bigint NULL,
    stats.totalPlayerScore bigint NULL,
    stats.totalScoreRank bigint NULL,
    stats.totalTimeCrowdControlDealt bigint NULL,
    stats.totalUnitsHealed bigint NULL,
    stats.tripleKills bigint NULL,
    stats.trueDamageDealt bigint NULL,
    stats.trueDamageDealtToChampions bigint NULL,
    stats.trueDamageTaken bigint NULL,
    stats.turretKills bigint NULL,
    stats.unrealKills bigint NULL,
    stats.visionScore bigint NULL,
    stats.visionWardsBoughtInGame bigint NULL,
    stats.wardsKilled bigint NULL,
    stats.wardsPlaced bigint NULL,
    stats.win boolean NULL,
    timeline.creepsPerMinDeltas.0_10 bigint precision NULL,
    timeline.creepsPerMinDeltas.10_20 bigint precision NULL,
    timeline.creepsPerMinDeltas.20_30 text NULL,
    timeline.creepsPerMinDeltas.30_end text NULL,
    timeline.csDiffPerMinDeltas.0_10 bigint precision NULL,
    timeline.csDiffPerMinDeltas.10_20 bigint precision NULL,
    timeline.csDiffPerMinDeltas.20_30 text NULL,
    timeline.csDiffPerMinDeltas.30_end text NULL,
    timeline.damageTakenDiffPerMinDeltas.0_10 bigint precision NULL,
    timeline.damageTakenDiffPerMinDeltas.10_20 bigint precision NULL,
    timeline.damageTakenDiffPerMinDeltas.20_30 text NULL,
    timeline.damageTakenDiffPerMinDeltas.30_end text NULL,
    timeline.damageTakenPerMinDeltas.0_10 bigint precision NULL,
    timeline.damageTakenPerMinDeltas.10_20 bigint precision NULL,
    timeline.damageTakenPerMinDeltas.20_30 text NULL,
    timeline.damageTakenPerMinDeltas.30_end text NULL,
    timeline.goldPerMinDeltas.0_10 bigint precision NULL,
    timeline.goldPerMinDeltas.10_20 bigint precision NULL,
    timeline.goldPerMinDeltas.20_30 text NULL,
    timeline.goldPerMinDeltas.30_end text NULL,
    timeline.lane text NULL,
    timeline.participantId bigint NULL,
    timeline.role text NULL,
    timeline.xpDiffPerMinDeltas.0_10 bigint precision NULL,
    timeline.xpDiffPerMinDeltas.10_20 bigint precision NULL,
    timeline.xpDiffPerMinDeltas.20_30 text NULL,
    timeline.xpDiffPerMinDeltas.30_end text NULL,
    timeline.xpPerMinDeltas.0_10 bigint precision NULL,
    timeline.xpPerMinDeltas.10_20 bigint precision NULL,
    timeline.xpPerMinDeltas.20_30 text NULL,
    timeline.xpPerMinDeltas.30_end text NULL
);


    game_stat['summoner_name'] = None; game_stat['summoner_id'] = None; game_stat['match.gameDuration'] = None; game_stat['match.gameId'] = None; game_stat['match.gameCreation'] = None; game_stat['match.gameMode'] = None; game_stat['match.gameType'] = None; game_stat['match.seasonId'] = None; game_stat['stats.win'] = None; game_stat['stats.item0'] = None; game_stat['stats.item1'] = None; game_stat['stats.item2'] = None; game_stat['stats.item3'] = None; game_stat['stats.item4'] = None; game_stat['stats.item5'] = None; game_stat['stats.item6'] = None; game_stat['stats.kills'] = None; game_stat['stats.perk0'] = None; game_stat['stats.perk1'] = None; game_stat['stats.perk2'] = None; game_stat['stats.perk3'] = None; game_stat['stats.perk4'] = None; game_stat['stats.perk5'] = None; game_stat['stats.deaths'] = None; game_stat['stats.assists'] = None; game_stat['stats.goldSpent'] = None; game_stat['stats.perk0Var1'] = None; game_stat['stats.perk0Var2'] = None; game_stat['stats.perk0Var3'] = None; game_stat['stats.perk1Var1'] = None; game_stat['stats.perk1Var2'] = None; game_stat['stats.perk1Var3'] = None; game_stat['stats.perk2Var1'] = None; game_stat['stats.perk2Var2'] = None; game_stat['stats.perk2Var3'] = None; game_stat['stats.perk3Var1'] = None; game_stat['stats.perk3Var2'] = None; game_stat['stats.perk3Var3'] = None; game_stat['stats.perk4Var1'] = None; game_stat['stats.perk4Var2'] = None; game_stat['stats.perk4Var3'] = None; game_stat['stats.perk5Var1'] = None; game_stat['stats.perk5Var2'] = None; game_stat['stats.perk5Var3'] = None; game_stat['stats.totalHeal'] = None; game_stat['stats.champLevel'] = None; game_stat['stats.goldEarned'] = None; game_stat['stats.pentaKills'] = None; game_stat['stats.doubleKills'] = None; game_stat['stats.quadraKills'] = None; game_stat['stats.tripleKills'] = None; game_stat['stats.turretKills'] = None; game_stat['stats.unrealKills'] = None; game_stat['stats.visionScore'] = None; game_stat['stats.wardsKilled'] = None; game_stat['stats.wardsPlaced'] = None; game_stat['stats.perkSubStyle'] = None; game_stat['stats.playerScore0'] = None; game_stat['stats.playerScore1'] = None; game_stat['stats.playerScore2'] = None; game_stat['stats.playerScore3'] = None; game_stat['stats.playerScore4'] = None; game_stat['stats.playerScore5'] = None; game_stat['stats.playerScore6'] = None; game_stat['stats.playerScore7'] = None; game_stat['stats.playerScore8'] = None; game_stat['stats.playerScore9'] = None; game_stat['stats.killingSprees'] = None; game_stat['stats.participantId'] = None; game_stat['stats.firstBloodKill'] = None; game_stat['stats.firstTowerKill'] = None; game_stat['stats.inhibitorKills'] = None; game_stat['stats.totalScoreRank'] = None; game_stat['stats.timeCCingOthers'] = None; game_stat['stats.trueDamageDealt'] = None; game_stat['stats.trueDamageTaken'] = None; game_stat['stats.firstBloodAssist'] = None; game_stat['stats.firstTowerAssist'] = None; game_stat['stats.largestMultiKill'] = None; game_stat['stats.magicDamageDealt'] = None; game_stat['stats.perkPrimaryStyle'] = None; game_stat['stats.totalDamageDealt'] = None; game_stat['stats.totalDamageTaken'] = None; game_stat['stats.totalPlayerScore'] = None; game_stat['stats.totalUnitsHealed'] = None; game_stat['stats.combatPlayerScore'] = None; game_stat['stats.firstInhibitorKill'] = None; game_stat['stats.magicalDamageTaken'] = None; game_stat['stats.totalMinionsKilled'] = None; game_stat['stats.damageSelfMitigated'] = None; game_stat['stats.largestKillingSpree'] = None; game_stat['stats.physicalDamageDealt'] = None; game_stat['stats.physicalDamageTaken'] = None; game_stat['stats.damageDealtToTurrets'] = None; game_stat['stats.firstInhibitorAssist'] = None; game_stat['stats.neutralMinionsKilled'] = None; game_stat['stats.objectivePlayerScore'] = None; game_stat['stats.largestCriticalStrike'] = None; game_stat['stats.longestTimeSpentLiving'] = None; game_stat['stats.sightWardsBoughtInGame'] = None; game_stat['stats.damageDealtToObjectives'] = None; game_stat['stats.visionWardsBoughtInGame'] = None; game_stat['stats.totalTimeCrowdControlDealt'] = None; game_stat['stats.trueDamageDealtToChampions'] = None; game_stat['stats.magicDamageDealtToChampions'] = None; game_stat['stats.totalDamageDealtToChampions'] = None; game_stat['stats.neutralMinionsKilledTeamJungle'] = None; game_stat['stats.physicalDamageDealtToChampions'] = None; game_stat['stats.neutralMinionsKilledEnemyJungle'] = None; game_stat['teamId'] = None; game_stat['spell1Id'] = None; game_stat['spell2Id'] = None; game_stat['timeline.lane'] = None; game_stat['timeline.role'] = None; game_stat['timeline.participantId'] = None; game_stat['timeline.xpPerMinDeltas.0_10'] = 0.00; game_stat['timeline.xpPerMinDeltas.10_20'] = 0.00; game_stat['timeline.xpPerMinDeltas.20_30'] = 0.00; game_stat['timeline.xpPerMinDeltas.30_end'] = 0.00; game_stat['timeline.goldPerMinDeltas.0_10'] = 0.00; game_stat['timeline.goldPerMinDeltas.10_20'] = 0.00; game_stat['timeline.goldPerMinDeltas.20_30'] = 0.00; game_stat['timeline.goldPerMinDeltas.30_end'] = 0.00; game_stat['timeline.creepsPerMinDeltas.0_10'] = 0.00; game_stat['timeline.creepsPerMinDeltas.10_20'] = 0.00; game_stat['timeline.creepsPerMinDeltas.20_30'] = 0.00; game_stat['timeline.creepsPerMinDeltas.30_end'] = 0.00; game_stat['timeline.csDiffPerMinDeltas.0_10'] = 0.00; game_stat['timeline.csDiffPerMinDeltas.10_20'] = 0.00; game_stat['timeline.csDiffPerMinDeltas.20_30'] = 0.00; game_stat['timeline.csDiffPerMinDeltas.30_end'] = 0.00; game_stat['timeline.xpDiffPerMinDeltas.0_10'] = 0.00; game_stat['timeline.xpDiffPerMinDeltas.10_20'] = 0.00; game_stat['timeline.xpDiffPerMinDeltas.20_30'] = 0.00; game_stat['timeline.xpDiffPerMinDeltas.30_end'] = 0.00; game_stat['timeline.damageTakenPerMinDeltas.0_10'] = 0.00; game_stat['timeline.damageTakenPerMinDeltas.10_20'] = 0.00; game_stat['timeline.damageTakenPerMinDeltas.20_30'] = 0.00; game_stat['timeline.damageTakenPerMinDeltas.30_end'] = 0.00; game_stat['timeline.damageTakenDiffPerMinDeltas.0_10'] = 0.00; game_stat['timeline.damageTakenDiffPerMinDeltas.10_20'] = 0.00; game_stat['timeline.damageTakenDiffPerMinDeltas.20_30'] = 0.00; game_stat['timeline.damageTakenDiffPerMinDeltas.30_end'] = 0.00; game_stat['championId'] = None; game_stat['participantId'] = None; game_stat['highestAchievedSeasonTier'] = None; game_stat['match.win'] = None
